### ISSUE TITLE
Fonts directory is undefined with ferret 7.2

### ISSUE THREAD

**Issue by Akshay-Hegde** [NOAA-PMEL/LAS#5]
With ferret 7.2 and las 8.6.1 I am getting strange error, actually my environment is alright

**Debug from ferret 7.2 though fondat.dat exists in ppl/fonts directory**
```
*** NOTE: Fonts directory is undefined. Check the Ferret environment.
 **ERROR: file undefined or not found: fondat.dat
SHADE/KEY=CONT/LEVELS=v/TRIM/LEVELS=v/TITLE="Chlorophyll-a Concentration (Milligrams per cubic meter)"/SET 'CHLA'[d=1,X=20:140,Y=-75:40,T="01-Jul-2009 00:00":"01-Jul-2009 00:00"]
...
```

**If I use ferret 7.1 no error**

```
root@las:/home/akshay# mv ferret/ ferret_7.2

root@las:/home/akshay# mv ferret_7.1/ ferret
```

**Debug from ferret 7.1**
```
Cached data cleared from memory
 LISTing to file /usr/local/www/html/TOMCAT_DEMO/tomcat/webapps/las/output/8E2BB0C551AB57ACEBFE2FB5EA117E01_map_scale.xml
 LISTing to file /usr/local/www/html/TOMCAT_DEMO/tomcat/webapps/las/output/8E2BB0C551AB57ACEBFE2FB5EA117E01_map_scale.xml
 LISTing to file /usr/local/www/html/TOMCAT_DEMO/tomcat/webapps/las/output/8E2BB0C551AB57ACEBFE2FB5EA117E01_map_scale.xml

```

[ferret_7.1_debug.txt](https://github.com/NOAA-PMEL/LAS/files/1167466/ferret_7.1_debug.txt)
[ferret_7.2_debug.txt](https://github.com/NOAA-PMEL/LAS/files/1167467/ferret_7.2_debug.txt)

**Comment by karlmsmith** [comment]
We discovered this error earlier about a week ago.  I checked in changes to the LAS code to fix this issue (commits 5664ec2ec9ea4401fb030a538ad48072c492d605 and 043497ecac2a7e20eacbac02dc32391f620dfa57 ).  **However**, Ferret (and PyFerret) 7.2 still has a bug that is very likely to cause problems with LAS.  So the best solution for now is to use Ferret (or PyFerret) v7.1

**Comment by Akshay-Hegde** [comment]
Ok thank you I will into into it.

But I noticed that ferret 7.1 consumes significantly more memory, for example the dataset which was working fine with old 6.9x started requesting about 1000 odd mega words on 64 bit OS, and ultimately ferrettool was throwing error.

**Comment by karlmsmith** [comment]
Prior to version 7.2 of ferret, a `SET MEM/SIZ=...` (where `...` is the number of memory to use in "mega-word"), that amount of memory would immediately be allocated.  Starting with version 7.2 that is just a limit and memory is only allocated as needed.  In the ferret scripts with LAS, depending on what it is try to do, these SET MEMORY /SIZE commands may but called to increase the amount of memory.  But I don't think any of the script will try to increase the value to the amount you mention with *typical* LAS usage. 

You can search (case-insensitive is best) for `SET MEM` in the `resources/ferret/scripts` subdirectory (under `JavaSource` in the source, or under `WEB-INF/classes` in under your installed application's directory in Tomcat's webapps directory) to see values that are getting set.  There are some large values for doing special operations, and maybe that is where you have problems.  You could try reducing these sizes, but ferret might start failing with not enough memory.

Do you have a $HOME/.ferret file that has this SET MEMORY /SIZE= command in it that sets such a large size?  This might be causing it to start in LAS with such a large size, but I am not sure.

**Comment by Akshay-Hegde** [comment]
I actually faced this memory issue while averaging data via `F-TDS`, the current scenario is like this I have daily data on my thredds server, using `F-TDS` I create monthly average, but performance is significantly better in `7.2` and in my `jnl` script where I average daily data I am not setting any memory and I don't have `$HOME/.ferret ` file

Also recently I create las.war file with `jdk 1.8` and `tomcat 7` I often get error message `too low setting for -Xss and illegal cyclic inheritance dependencies`

I have `-Xmx2048m -Xms1024m -server`

Which environment you guys are developing ?
Can you share you 

```
echo $JAVA_HOME
echo $JAVA_OPTS
echo $CATALINA_OPTS 
```

**Comment by karlmsmith** [comment]
Because we are using LAS on some very large datasets, our Java memory limit settings will probably be larger that usual. But your memory limits look fine **if** you have that much memory readily available (and don't mind have it taken up) on your system.  But if you are running into out-of-memory issues, you will want to lower those; at least lower the initial heap memory (-Xms) setting - probably don't really need it at all.  Setting -Xmx too large can get you into memory swapping, which is never good, or other memory issues.  You can get some help on the settings from `java -help` for standard settings and `java -X` for non-standard settings (like the -Xmx, -Xms, and -Xss)

As for the Java version, we try to keep up-to-date with the latest Java-8 from Oracle.  As for settings, one of our system we us internally has `-server -d64 -Xmx4096M -Xms1024M -Djava.awt.headless=true` for JAVA_OPTS and nothing for CATALINA_OPTS.  But this system has 128G memory so (up to) 4G for Java heap space is a minor allocation.  I have these set in a file `setenv.sh` in the Tomcat bin subdirectory - Tomcat automatically reads that file for these environment settings.

**Comment by Akshay-Hegde** [comment]
Thank you so much for your valuable response. As you suggested I will
modify those values and will try, Have a nice day.
